# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rox/Documents/Code/Heni/peugeot/edge_based_tracker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rox/Documents/Code/Heni/peugeot/edge_based_tracker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rox/Documents/Code/Heni/peugeot/edge_based_tracker/CMakeFiles /home/rox/Documents/Code/Heni/peugeot/edge_based_tracker/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rox/Documents/Code/Heni/peugeot/edge_based_tracker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EBT

# Build rule for target.
EBT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EBT
.PHONY : EBT

# fast build rule for target.
EBT/fast:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/build
.PHONY : EBT/fast

#=============================================================================
# Target rules for targets named edge_templates_generator

# Build rule for target.
edge_templates_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edge_templates_generator
.PHONY : edge_templates_generator

# fast build rule for target.
edge_templates_generator/fast:
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/build
.PHONY : edge_templates_generator/fast

#=============================================================================
# Target rules for targets named ImageLib

# Build rule for target.
ImageLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageLib
.PHONY : ImageLib

# fast build rule for target.
ImageLib/fast:
	$(MAKE) -f Image/CMakeFiles/ImageLib.dir/build.make Image/CMakeFiles/ImageLib.dir/build
.PHONY : ImageLib/fast

#=============================================================================
# Target rules for targets named LineFitLib

# Build rule for target.
LineFitLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LineFitLib
.PHONY : LineFitLib

# fast build rule for target.
LineFitLib/fast:
	$(MAKE) -f Fitline/CMakeFiles/LineFitLib.dir/build.make Fitline/CMakeFiles/LineFitLib.dir/build
.PHONY : LineFitLib/fast

#=============================================================================
# Target rules for targets named FdcmLib

# Build rule for target.
FdcmLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FdcmLib
.PHONY : FdcmLib

# fast build rule for target.
FdcmLib/fast:
	$(MAKE) -f Fdcm/CMakeFiles/FdcmLib.dir/build.make Fdcm/CMakeFiles/FdcmLib.dir/build
.PHONY : FdcmLib/fast

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/Camera.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/Camera.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/Camera.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/EdgeTracker.o: src/EdgeTracker.cpp.o
.PHONY : src/EdgeTracker.o

# target to build an object file
src/EdgeTracker.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/EdgeTracker.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/EdgeTracker.cpp.o
.PHONY : src/EdgeTracker.cpp.o

src/EdgeTracker.i: src/EdgeTracker.cpp.i
.PHONY : src/EdgeTracker.i

# target to preprocess a source file
src/EdgeTracker.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/EdgeTracker.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/EdgeTracker.cpp.i
.PHONY : src/EdgeTracker.cpp.i

src/EdgeTracker.s: src/EdgeTracker.cpp.s
.PHONY : src/EdgeTracker.s

# target to generate assembly for a file
src/EdgeTracker.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/EdgeTracker.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/EdgeTracker.cpp.s
.PHONY : src/EdgeTracker.cpp.s

src/HomoTransform.o: src/HomoTransform.cpp.o
.PHONY : src/HomoTransform.o

# target to build an object file
src/HomoTransform.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/HomoTransform.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/HomoTransform.cpp.o
.PHONY : src/HomoTransform.cpp.o

src/HomoTransform.i: src/HomoTransform.cpp.i
.PHONY : src/HomoTransform.i

# target to preprocess a source file
src/HomoTransform.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/HomoTransform.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/HomoTransform.cpp.i
.PHONY : src/HomoTransform.cpp.i

src/HomoTransform.s: src/HomoTransform.cpp.s
.PHONY : src/HomoTransform.s

# target to generate assembly for a file
src/HomoTransform.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/HomoTransform.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/HomoTransform.cpp.s
.PHONY : src/HomoTransform.cpp.s

src/ParticleFilter.o: src/ParticleFilter.cpp.o
.PHONY : src/ParticleFilter.o

# target to build an object file
src/ParticleFilter.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/ParticleFilter.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/ParticleFilter.cpp.o
.PHONY : src/ParticleFilter.cpp.o

src/ParticleFilter.i: src/ParticleFilter.cpp.i
.PHONY : src/ParticleFilter.i

# target to preprocess a source file
src/ParticleFilter.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/ParticleFilter.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/ParticleFilter.cpp.i
.PHONY : src/ParticleFilter.cpp.i

src/ParticleFilter.s: src/ParticleFilter.cpp.s
.PHONY : src/ParticleFilter.s

# target to generate assembly for a file
src/ParticleFilter.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/ParticleFilter.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/ParticleFilter.cpp.s
.PHONY : src/ParticleFilter.cpp.s

src/PoseEstimationSURF.o: src/PoseEstimationSURF.cpp.o
.PHONY : src/PoseEstimationSURF.o

# target to build an object file
src/PoseEstimationSURF.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/PoseEstimationSURF.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/PoseEstimationSURF.cpp.o
.PHONY : src/PoseEstimationSURF.cpp.o

src/PoseEstimationSURF.i: src/PoseEstimationSURF.cpp.i
.PHONY : src/PoseEstimationSURF.i

# target to preprocess a source file
src/PoseEstimationSURF.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/PoseEstimationSURF.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/PoseEstimationSURF.cpp.i
.PHONY : src/PoseEstimationSURF.cpp.i

src/PoseEstimationSURF.s: src/PoseEstimationSURF.cpp.s
.PHONY : src/PoseEstimationSURF.s

# target to generate assembly for a file
src/PoseEstimationSURF.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/PoseEstimationSURF.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/PoseEstimationSURF.cpp.s
.PHONY : src/PoseEstimationSURF.cpp.s

src/edge_templates_generator.o: src/edge_templates_generator.cpp.o
.PHONY : src/edge_templates_generator.o

# target to build an object file
src/edge_templates_generator.cpp.o:
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/edge_templates_generator.cpp.o
.PHONY : src/edge_templates_generator.cpp.o

src/edge_templates_generator.i: src/edge_templates_generator.cpp.i
.PHONY : src/edge_templates_generator.i

# target to preprocess a source file
src/edge_templates_generator.cpp.i:
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/edge_templates_generator.cpp.i
.PHONY : src/edge_templates_generator.cpp.i

src/edge_templates_generator.s: src/edge_templates_generator.cpp.s
.PHONY : src/edge_templates_generator.s

# target to generate assembly for a file
src/edge_templates_generator.cpp.s:
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/edge_templates_generator.cpp.s
.PHONY : src/edge_templates_generator.cpp.s

src/epnp.o: src/epnp.cpp.o
.PHONY : src/epnp.o

# target to build an object file
src/epnp.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/epnp.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/epnp.cpp.o
.PHONY : src/epnp.cpp.o

src/epnp.i: src/epnp.cpp.i
.PHONY : src/epnp.i

# target to preprocess a source file
src/epnp.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/epnp.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/epnp.cpp.i
.PHONY : src/epnp.cpp.i

src/epnp.s: src/epnp.cpp.s
.PHONY : src/epnp.s

# target to generate assembly for a file
src/epnp.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/epnp.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/epnp.cpp.s
.PHONY : src/epnp.cpp.s

src/glm.o: src/glm.cpp.o
.PHONY : src/glm.o

# target to build an object file
src/glm.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/glm.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/glm.cpp.o
.PHONY : src/glm.cpp.o

src/glm.i: src/glm.cpp.i
.PHONY : src/glm.i

# target to preprocess a source file
src/glm.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/glm.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/glm.cpp.i
.PHONY : src/glm.cpp.i

src/glm.s: src/glm.cpp.s
.PHONY : src/glm.s

# target to generate assembly for a file
src/glm.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/glm.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/glm.cpp.s
.PHONY : src/glm.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objectmodel.o: src/objectmodel.cpp.o
.PHONY : src/objectmodel.o

# target to build an object file
src/objectmodel.cpp.o:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/objectmodel.cpp.o
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/objectmodel.cpp.o
.PHONY : src/objectmodel.cpp.o

src/objectmodel.i: src/objectmodel.cpp.i
.PHONY : src/objectmodel.i

# target to preprocess a source file
src/objectmodel.cpp.i:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/objectmodel.cpp.i
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/objectmodel.cpp.i
.PHONY : src/objectmodel.cpp.i

src/objectmodel.s: src/objectmodel.cpp.s
.PHONY : src/objectmodel.s

# target to generate assembly for a file
src/objectmodel.cpp.s:
	$(MAKE) -f CMakeFiles/EBT.dir/build.make CMakeFiles/EBT.dir/src/objectmodel.cpp.s
	$(MAKE) -f CMakeFiles/edge_templates_generator.dir/build.make CMakeFiles/edge_templates_generator.dir/src/objectmodel.cpp.s
.PHONY : src/objectmodel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... EBT"
	@echo "... edge_templates_generator"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ImageLib"
	@echo "... LineFitLib"
	@echo "... FdcmLib"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/EdgeTracker.o"
	@echo "... src/EdgeTracker.i"
	@echo "... src/EdgeTracker.s"
	@echo "... src/HomoTransform.o"
	@echo "... src/HomoTransform.i"
	@echo "... src/HomoTransform.s"
	@echo "... src/ParticleFilter.o"
	@echo "... src/ParticleFilter.i"
	@echo "... src/ParticleFilter.s"
	@echo "... src/PoseEstimationSURF.o"
	@echo "... src/PoseEstimationSURF.i"
	@echo "... src/PoseEstimationSURF.s"
	@echo "... src/edge_templates_generator.o"
	@echo "... src/edge_templates_generator.i"
	@echo "... src/edge_templates_generator.s"
	@echo "... src/epnp.o"
	@echo "... src/epnp.i"
	@echo "... src/epnp.s"
	@echo "... src/glm.o"
	@echo "... src/glm.i"
	@echo "... src/glm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objectmodel.o"
	@echo "... src/objectmodel.i"
	@echo "... src/objectmodel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

